[package]
version = "0.1.0"
name = "litmus-zk-script"
edition = "2021"
default-run = "litmus-zk"

[[bin]]
name = "litmus-zk"
path = "src/bin/main.rs"

[[bin]]
name = "vkey"
path = "src/bin/vkey.rs"

[dependencies]
clap = { version = "4.0", features = ["derive", "env"] }
hex = "0.4.3"
litmus-zk-lib = { path = "../lib" }
sp1-sdk = "1.2.0"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
tracing = "0.1.40"

[build-dependencies]
sp1-helper = "1.2.0"
